<?php
/**
 * Created by PhpStorm.
 * User: Christoph
 * Date: 23.07.2016
 * Time: 20:58
 */

namespace JamylBot\Console\Commands;

use Illuminate\Console\Command;
use JamylBot\Group;
use JamylBot\User;

class UpdateUserGroups extends Command
{
    /**
     * The console command name.
     *
     * @var string
     */
    protected $name = 'jamyl:usergroups';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Update group membership based on corp id';

    /**
     * Create a new command instance.
     *
     */
    public function __construct()
    {
        parent::__construct();
    }

    public function fire()
    {
        foreach(User::all() as $user) {
            foreach(Group::all() as $group) {
                if(count($group->getCorps())) {
                    if ($group->hasCorp($user->corp_id)) {
                        $group->users()->attach($user);
                    } else {
                        $group->users()->detach($user);
                    }
                    $group->save();
                }
            }
        }
    }

    protected function getArguments()
    {
        return parent::getArguments(); // TODO: Change the autogenerated stub
    }

    /**
     * Get the console command options.
     *
     * @return array
     */
    protected function getOptions()
    {
        return [
//			['example', null, InputOption::VALUE_OPTIONAL, 'An example option.', null],
        ];
    }

}